# Generated by Django 5.1.1 on 2024-10-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='First', max_length=15)),
                ('email', models.EmailField(default='Email', max_length=50)),
                ('password', models.CharField(default='Passwd', max_length=250)),
            ],
        ),
    ]
